version: "3.7"
services:
  mysql:
    image: mysql:8.0.31
    ports:
      - "8030:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=careerclub
  careerclub:
    build:
      context: .
    image: eoluoch/career-club
    depends_on:
      - "mysql"
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - AWS_ACCESS_KEY_ID=${S3_KEY}
      - AWS_REGION=us-east-2
      - AWS_SECRET_ACCESS_KEY=${S3_SECRET}
      - SPRING_MAIL_USERNAME=${MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${MAIL_PASSWORD}




