version: "1"
services:
  mysql:
    image: mysql:8.0.31
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=careerclub
  careerclub:
    image: eoluoch/career-club
    depends_on:
      - "mysql"
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://carrersclub-mysql-1:3306/careerclub
      - AWS_ACCESS_KEY_ID=AKIASNPQTJPGLJRHTQAR
      - AWS_REGION=us-east-2
      - AWS_SECRET_ACCESS_KEY=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
      - SPRING_MAIL_USERNAME=cd5d63c9b70b14
      - SPRING_MAIL_PASSWORD=d53efc98134f07



