on:
  push:
    branches : ["master"]
  pull_request:
    branches: ["master"]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout from repo
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    - name: Runs test
      run: ./mvnw test
  package:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout from repo
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Packaging the application
        run: ./mvnw package -DskipTests

      - name: Archive jar
        uses: actions/upload-artifact@v3
        with:
          name: carrersclub-jars
          path: target/*.jar
  deploy:
    needs: package
    runs-on: ubuntu-latest
    name: Deploy to oracle
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download JAR
        uses: actions/download-artifact@v3
        with:
          name: 'carrersclub-jars'
          path: ~/carrersclub-jars

      - name: create deploy key
        run:  |
          echo "${{secrets.ORACLE_SSH_KEY}}" > deploy_key
          chmod 600 ./deploy_key
      - name: Create jar folder on remote machine
        run: |
          ssh -i ./deploy_key -o 'StrictHostKeyChecking=no' opc@${{ secrets.ORACLE_VM_PUBLIC_IP }} 'mkdir -p carrersclub-jars'
      - name: Rsynch files
        run: |
          rsync -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' -avzr --progress ~/carrersclub-jars/*.jar opc@${{ secrets.ORACLE_VM_PUBLIC_IP }}:~/carrersclub-jars/app.jar
      - name: Restart application
        run: |
          ssh -i ./deploy_key -o "StrictHostKeyChecking=no" opc@${{ secrets.ORACLE_VM_PUBLIC_IP }} 'sudo chmod +x $HOME/carrersclub-jars/app.jar'
          ssh -i ./deploy_key -o "StrictHostKeyChecking=no" opc@${{ secrets.ORACLE_VM_PUBLIC_IP }} 'sudo systemctl restart carrersclub_app.service'